
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GTEQ = 15;
  public static final int OVER = 19;
  public static final int LTEQ = 13;
  public static final int UMINUS = 23;
  public static final int LPAREN = 24;
  public static final int SEMI = 30;
  public static final int INT = 5;
  public static final int MINUS = 17;
  public static final int RPAREN = 25;
  public static final int NOT = 22;
  public static final int AND = 20;
  public static final int LT = 12;
  public static final int OR = 21;
  public static final int BOOL = 4;
  public static final int COMMA = 31;
  public static final int NUM = 33;
  public static final int PLUS = 16;
  public static final int ASSIGN = 9;
  public static final int IF = 2;
  public static final int ID = 32;
  public static final int EOF = 0;
  public static final int RETURN = 6;
  public static final int error = 1;
  public static final int NEQ = 11;
  public static final int VOID = 7;
  public static final int EQ = 10;
  public static final int ERROR = 35;
  public static final int LBRACK = 28;
  public static final int TRUTH = 34;
  public static final int TIMES = 18;
  public static final int LBRACE = 26;
  public static final int ELSE = 3;
  public static final int RBRACK = 29;
  public static final int WHILE = 8;
  public static final int RBRACE = 27;
  public static final int GT = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "BOOL",
  "INT",
  "RETURN",
  "VOID",
  "WHILE",
  "ASSIGN",
  "EQ",
  "NEQ",
  "LT",
  "LTEQ",
  "GT",
  "GTEQ",
  "PLUS",
  "MINUS",
  "TIMES",
  "OVER",
  "AND",
  "OR",
  "NOT",
  "UMINUS",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACK",
  "RBRACK",
  "SEMI",
  "COMMA",
  "ID",
  "NUM",
  "TRUTH",
  "ERROR"
  };
}

